services:
  doc:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dot_pnpm-store:/app/.pnpm-store
volumes:
  node_modules:
  dot_pnpm-store:
